import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, CheckCircle2, Clock3, ExternalLink, Loader2, MessageSquare, Settings2, Tag, Wrench } from "lucide-react";
import { Link, useLocation } from "wouter";

export default function BusinessTools({ businessId, businessName }: { businessId: number; businessName: string }) {
  const [location] = useLocation();
  const tool = location.split("/").at(-1) ?? "overview";
  const labels: Record<string, string> = { hours: "Hours", services: "Services & items", leads: "Lead inbox", reviews: "Reviews", offers: "Offers", settings: "Settings" };
  return <div className="min-h-screen bg-[#f6f8fc] text-slate-950"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-4 sm:px-6"><Link href="/business" className="inline-flex items-center gap-2 text-sm font-semibold"><ArrowLeft className="size-4" />Business workspace</Link><span className="text-xs text-slate-500">{businessName}</span></div></header><main className="mx-auto max-w-6xl px-4 py-8 sm:px-6"><div className="flex flex-wrap gap-2">{Object.entries(labels).map(([key, label]) => <Link key={key} href={`/business/${businessId}/${key}`} className={`rounded-xl px-3 py-2 text-sm font-medium ${tool === key ? "bg-[#173d9c] text-white" : "bg-white text-slate-600 ring-1 ring-slate-200 hover:bg-blue-50"}`}>{label}</Link>)}</div><section className="mt-6 rounded-[28px] border border-slate-200 bg-white p-6 sm:p-8"><div className="flex items-start gap-4"><div className="grid size-11 place-items-center rounded-2xl bg-blue-50 text-[#2456c8]"><ToolIcon tool={tool} /></div><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#2456c8]">Owner tool</p><h1 className="mt-1 text-2xl font-semibold tracking-[-.04em]">{labels[tool] ?? "Workspace"}</h1><p className="mt-2 text-sm text-slate-500">Changes are scoped to this business and remain private until approved.</p></div></div><ToolContent tool={tool} businessId={businessId} /></section></main></div>;
}

function ToolIcon({ tool }: { tool: string }) { if (tool === "hours") return <Clock3 className="size-5" />; if (tool === "reviews") return <MessageSquare className="size-5" />; if (tool === "offers") return <Tag className="size-5" />; if (tool === "settings") return <Settings2 className="size-5" />; return <Wrench className="size-5" />; }
function ToolContent({ tool, businessId }: { tool: string; businessId: number }) {
  if (tool === "leads") { const q = trpc.business.listLeads.useQuery({ businessId }); if (q.isLoading) return <Loader />; return <div className="mt-8 space-y-3">{q.data?.length ? q.data.map(lead => <div key={lead.id} className="rounded-2xl bg-slate-50 p-4"><div className="flex justify-between gap-3"><p className="font-medium">{lead.name || "Unnamed enquiry"}</p><span className="text-xs capitalize text-slate-500">{lead.status}</span></div><p className="mt-1 text-sm text-slate-500">{lead.email || lead.phone || "Contact details not provided"}</p><p className="mt-2 text-sm text-slate-600">{lead.message || "No message"}</p></div>) : <Empty title="No enquiries yet" text="New customer enquiries will appear here when they arrive." />}</div>; }
  if (tool === "reviews") { const q = trpc.business.listReviews.useQuery({ businessId }); if (q.isLoading) return <Loader />; return <div className="mt-8 space-y-3">{q.data?.length ? q.data.map(review => <div key={review.id} className="rounded-2xl bg-slate-50 p-4"><div className="flex justify-between gap-3"><p className="font-medium">{"Verified customer"}</p><span className="text-sm font-semibold text-amber-600">{review.rating}/5</span></div><p className="mt-2 text-sm leading-6 text-slate-600">{review.content || "No written comment"}</p></div>) : <Empty title="No reviews to respond to" text="Authentic customer feedback will appear here. Never add or invent reviews." />}</div>; }
  if (tool === "offers") { const q = trpc.business.listOffers.useQuery({ businessId }); if (q.isLoading) return <Loader />; return <div className="mt-8 space-y-3">{q.data?.length ? q.data.map(offer => <div key={offer.id} className="rounded-2xl bg-slate-50 p-4"><div className="flex justify-between gap-3"><p className="font-medium">{offer.title}</p><span className="text-xs capitalize text-slate-500">{offer.status}</span></div><p className="mt-2 text-sm text-slate-600">{offer.description || "No description"}</p></div>) : <Empty title="No offers published" text="Create a factual offer when you have a current promotion to share." />}</div>; }
  return <div className="mt-8 grid gap-4 sm:grid-cols-2">{tool === "hours" && <Empty title="Weekly hours" text="Set regular and special hours from this owner-scoped workspace." action="Open hours editor" />}{tool === "services" && <Empty title="Services and items" text="Keep your current offerings, menu items, or rooms clear and up to date." action="Add an offering" />}{tool === "settings" && <Empty title="Workspace settings" text="Manage notification preferences, public profile links, and owner controls." action="Review settings" />}{!['hours','services','settings'].includes(tool) && <Empty title="Choose a workspace tool" text="Use the navigation above to manage this business." />}</div>;
}
function Loader() { return <div className="mt-8 grid place-items-center py-12"><Loader2 className="size-6 animate-spin text-[#2456c8]" /></div>; }
function Empty({ title, text, action }: { title: string; text: string; action?: string }) { return <div className="rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-6"><div className="flex items-center gap-2"><CheckCircle2 className="size-5 text-emerald-600" /><h2 className="font-semibold">{title}</h2></div><p className="mt-2 max-w-xl text-sm leading-6 text-slate-500">{text}</p>{action && <Button variant="outline" className="mt-4 rounded-xl">{action}<ExternalLink className="ml-2 size-4" /></Button>}</div>; }
