import { PageFrame } from "@/components/PageFrame";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ArrowRight, BriefcaseBusiness, Building2, ChevronRight, HeartPulse, Home, Landmark, Search, Sparkles, UtensilsCrossed } from "lucide-react";
import { useEffect, useState } from "react";
import { Link } from "wouter";

const categoryIcons: Record<string, React.ElementType> = { healthcare: HeartPulse, "food-dining": UtensilsCrossed, education: Landmark, "home-services": Home, "professional-services": Building2, jobs: BriefcaseBusiness };
const categoryColors = ["bg-blue-50 text-blue-600", "bg-orange-50 text-orange-600", "bg-emerald-50 text-emerald-600", "bg-violet-50 text-violet-600", "bg-amber-50 text-amber-700", "bg-sky-50 text-sky-600"];

export default function Categories() {
  const { data, isLoading } = trpc.discovery.categories.useQuery();
  const [activeSlug, setActiveSlug] = useState<string | undefined>();
  useEffect(() => { if (!activeSlug && data?.[0]) setActiveSlug(data[0].slug); }, [activeSlug, data]);
  const active = data?.find(category => category.slug === activeSlug) ?? data?.[0];
  const ActiveIcon = active ? (categoryIcons[active.slug] ?? Building2) : Building2;

  return <PageFrame>
    <section className="border-b border-[var(--jf-border)] bg-white py-12 sm:py-16"><div className="container text-center"><span className="jf-kicker"><Sparkles className="size-3.5" />Browse local categories</span><h1 className="mt-5 text-4xl font-bold tracking-[-.06em] text-[var(--jf-text)] sm:text-5xl">Find the right category,<br /><span className="text-[var(--jf-primary)]">then the right local place.</span></h1><p className="mx-auto mt-4 max-w-2xl text-sm leading-7 text-[var(--jf-muted)] sm:text-base">Browse the categories available in Just Finds, then continue into a local search using published business profiles.</p><Link href="/search"><Button className="jf-action-primary mt-6 px-5">Search businesses <Search className="ml-2 size-4" /></Button></Link></div></section>
    <section className="container py-10 sm:py-14"><div className="mb-5 flex items-center gap-2 text-xs text-[var(--jf-muted)]"><Link href="/" className="hover:text-[var(--jf-primary)]">Home</Link><ChevronRight className="size-3.5" /><span className="font-semibold text-[var(--jf-text)]">Categories</span></div><div className="grid gap-6 lg:grid-cols-[236px_minmax(0,1fr)]"><aside className="jf-card rounded-[22px] p-3"><p className="px-3 pb-2 pt-1 text-xs font-bold uppercase tracking-[.14em] text-[var(--jf-muted)]">Browse categories</p><div className="grid gap-1">{isLoading ? [...Array(5)].map((_, index) => <div key={index} className="h-10 animate-pulse rounded-xl bg-slate-100" />) : data?.map((category, index) => { const Icon = categoryIcons[category.slug] ?? Building2; const selected = active?.slug === category.slug; return <button type="button" key={category.id} onClick={() => setActiveSlug(category.slug)} className={`flex items-center justify-between gap-3 rounded-xl px-3 py-2.5 text-left text-sm font-semibold transition-colors ${selected ? "bg-blue-50 text-[var(--jf-primary)]" : "text-slate-700 hover:bg-slate-50"}`}><span className="flex min-w-0 items-center gap-2.5"><span className={`grid size-7 shrink-0 place-items-center rounded-lg ${categoryColors[index % categoryColors.length]}`}><Icon className="size-3.5" /></span><span className="truncate">{category.name}</span></span><ChevronRight className="size-3.5 shrink-0" /></button>; })}</div></aside>
      <div className="jf-card rounded-[22px] p-5 sm:p-7">{active ? <><div className="flex flex-col gap-4 border-b border-[var(--jf-border)] pb-6 sm:flex-row sm:items-start sm:justify-between"><div className="flex gap-4"><span className={`grid size-13 shrink-0 place-items-center rounded-2xl ${categoryColors[(data?.findIndex(category => category.slug === active.slug) ?? 0) % categoryColors.length]}`}><ActiveIcon className="size-6" /></span><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[var(--jf-primary)]">Category overview</p><h2 className="mt-1 text-2xl font-bold tracking-[-.045em] text-[var(--jf-text)] sm:text-3xl">{active.name}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[var(--jf-muted)]">{active.description ?? "Browse businesses and services that have been published in this category."}</p></div></div><Link href={`/search?category=${active.slug}`} className="jf-action-primary inline-flex shrink-0 items-center justify-center gap-2 px-4 py-2.5 text-sm font-semibold">Explore {active.name}<ArrowRight className="size-4" /></Link></div><div className="mt-7"><p className="text-sm font-bold text-[var(--jf-text)]">Available local categories</p><p className="mt-1 text-xs leading-5 text-[var(--jf-muted)]">Choose a category to search the published profiles associated with it.</p><div className="mt-5 grid grid-cols-2 gap-3 xl:grid-cols-3">{(data ?? []).map((category, index) => { const Icon = categoryIcons[category.slug] ?? Building2; return <Link href={`/search?category=${category.slug}`} key={category.id} className="jf-card-interactive rounded-2xl border border-[var(--jf-border)] bg-white p-3.5 sm:p-4"><span className={`grid size-9 place-items-center rounded-xl ${categoryColors[index % categoryColors.length]}`}><Icon className="size-4" /></span><p className="mt-3 text-sm font-bold text-[var(--jf-text)]">{category.name}</p><p className="mt-1 line-clamp-2 text-xs leading-5 text-[var(--jf-muted)]">{category.description ?? "Explore published local profiles."}</p><span className="mt-3 inline-flex items-center gap-1 text-xs font-bold text-[var(--jf-primary)]">Explore <ArrowRight className="size-3.5 transition-transform group-hover:translate-x-0.5" /></span></Link>; })}</div></div></> : <div className="py-12 text-center text-sm text-[var(--jf-muted)]">Categories will appear once they are available.</div>}</div></div></section>
  </PageFrame>;
}
