import { PageFrame } from "@/components/PageFrame";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ArrowRight, BriefcaseBusiness, Building2, ChevronRight, HeartPulse, Home, Landmark, Search, Sparkles, UtensilsCrossed } from "lucide-react";
import { useEffect, useState } from "react";
import { Link } from "wouter";

const categoryIcons: Record<string, React.ElementType> = { healthcare: HeartPulse, "food-dining": UtensilsCrossed, education: Landmark, "home-services": Home, "professional-services": Building2, jobs: BriefcaseBusiness };
const categoryColors = ["bg-[#e7efff] text-[#2859d8]", "bg-[#fff0e6] text-[#df762f]", "bg-[#eaf6ef] text-[#23825a]", "bg-[#f4edfc] text-[#7c43b2]", "bg-[#fff5da] text-[#9c6b1e]", "bg-[#e8f5f7] text-[#147c8c]"];

export default function Categories() {
  const { data, isLoading } = trpc.discovery.categories.useQuery();
  const [activeSlug, setActiveSlug] = useState<string | undefined>();
  useEffect(() => { if (!activeSlug && data?.[0]) setActiveSlug(data[0].slug); }, [activeSlug, data]);
  const active = data?.find(category => category.slug === activeSlug) ?? data?.[0];
  const ActiveIcon = active ? (categoryIcons[active.slug] ?? Building2) : Building2;

  return <PageFrame>
    <section className="border-b border-[#e8edf6] bg-[linear-gradient(180deg,#fbfcff,#f4f7ff)] py-12 sm:py-16"><div className="container text-center"><span className="inline-flex items-center gap-2 rounded-full border border-[#dce5fb] bg-white px-3 py-1.5 text-xs font-semibold text-[#3159c7] shadow-sm"><Sparkles className="size-3.5" />Browse local categories</span><h1 className="mt-5 text-4xl font-bold tracking-[-.06em] text-[#0c1d4a] sm:text-5xl">Find the right category,<br /><span className="text-[#315cf3]">then the right local place.</span></h1><p className="mx-auto mt-4 max-w-2xl text-sm leading-7 text-slate-600 sm:text-base">Browse the categories available in Just Finds, then continue into a local search using real published business profiles.</p><Link href="/search"><Button className="mt-6 rounded-lg bg-[#2f5bea] px-5 shadow-[0_9px_18px_rgba(47,91,234,.18)] hover:bg-[#244bd0]">Search businesses <Search className="ml-2 size-4" /></Button></Link></div></section>
    <section className="container py-10 sm:py-14"><div className="mb-5 flex items-center gap-2 text-xs text-slate-500"><Link href="/" className="hover:text-[#315cf3]">Home</Link><ChevronRight className="size-3.5" /><span className="font-semibold text-slate-700">Categories</span></div><div className="grid gap-6 lg:grid-cols-[236px_minmax(0,1fr)]"><aside className="rounded-2xl border border-[#e8edf6] bg-white p-3 shadow-[0_4px_14px_rgba(15,36,82,.035)]"><p className="px-3 pb-2 pt-1 text-xs font-bold uppercase tracking-[.14em] text-slate-500">Browse categories</p><div className="grid gap-1">{isLoading ? [...Array(5)].map((_, index) => <div key={index} className="h-10 animate-pulse rounded-lg bg-slate-100" />) : data?.map((category, index) => { const Icon = categoryIcons[category.slug] ?? Building2; const selected = active?.slug === category.slug; return <button type="button" key={category.id} onClick={() => setActiveSlug(category.slug)} className={`flex items-center justify-between gap-3 rounded-xl px-3 py-2.5 text-left text-sm font-semibold transition-colors ${selected ? "bg-[#edf2ff] text-[#2859d8]" : "text-slate-700 hover:bg-[#f7f9ff]"}`}><span className="flex min-w-0 items-center gap-2.5"><span className={`grid size-7 shrink-0 place-items-center rounded-lg ${categoryColors[index % categoryColors.length]}`}><Icon className="size-3.5" /></span><span className="truncate">{category.name}</span></span><ChevronRight className="size-3.5 shrink-0" /></button>; })}</div></aside>
      <div className="rounded-2xl border border-[#e8edf6] bg-white p-5 shadow-[0_4px_14px_rgba(15,36,82,.035)] sm:p-7">{active ? <><div className="flex flex-col gap-4 border-b border-[#edf0f6] pb-6 sm:flex-row sm:items-start sm:justify-between"><div className="flex gap-4"><span className={`grid size-13 shrink-0 place-items-center rounded-2xl ${categoryColors[(data?.findIndex(category => category.slug === active.slug) ?? 0) % categoryColors.length]}`}><ActiveIcon className="size-6" /></span><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#315cf3]">Category overview</p><h2 className="mt-1 text-2xl font-bold tracking-[-.045em] text-[#10214d] sm:text-3xl">{active.name}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">{active.description ?? "Browse businesses and services that have been published in this category."}</p></div></div><Link href={`/search?category=${active.slug}`} className="inline-flex shrink-0 items-center justify-center gap-2 rounded-lg bg-[#2f5bea] px-4 py-2.5 text-sm font-semibold text-white shadow-[0_8px_16px_rgba(47,91,234,.16)] hover:bg-[#244bd0]">Explore {active.name}<ArrowRight className="size-4" /></Link></div><div className="mt-7"><p className="text-sm font-bold text-[#17264b]">Available local categories</p><p className="mt-1 text-xs leading-5 text-slate-500">Choose a category to search the published profiles associated with it.</p><div className="mt-5 grid grid-cols-2 gap-3 xl:grid-cols-3">{(data ?? []).map((category, index) => { const Icon = categoryIcons[category.slug] ?? Building2; return <Link href={`/search?category=${category.slug}`} key={category.id} className="group rounded-xl border border-[#edf0f6] bg-[#fcfdff] p-3.5 transition-[border-color,box-shadow,transform] hover:-translate-y-0.5 hover:border-[#c8d6fb] hover:shadow-[0_10px_20px_rgba(30,65,160,.07)] sm:p-4"><span className={`grid size-9 place-items-center rounded-xl ${categoryColors[index % categoryColors.length]}`}><Icon className="size-4" /></span><p className="mt-3 text-sm font-bold text-[#17264b]">{category.name}</p><p className="mt-1 line-clamp-2 text-xs leading-5 text-slate-500">{category.description ?? "Explore published local profiles."}</p><span className="mt-3 inline-flex items-center gap-1 text-xs font-bold text-[#315cf3]">Explore <ArrowRight className="size-3.5 transition-transform group-hover:translate-x-0.5" /></span></Link>; })}</div></div></> : <div className="py-12 text-center text-sm text-slate-500">Categories will appear once they are available.</div>}</div></div></section>
  </PageFrame>;
}
