import { Button } from "@/components/ui/button";
import { BusinessCard, BusinessCardData } from "@/components/BusinessCard";
import { LocationPill, PageFrame } from "@/components/PageFrame";
import { SearchHero } from "@/components/SearchHero";
import { trpc } from "@/lib/trpc";
import { ArrowRight, BadgeCheck, BriefcaseBusiness, Building2, ChevronRight, Compass, HeartPulse, Hotel, MapPinned, Sparkles, Utensils, Wrench } from "lucide-react";
import { useMemo } from "react";
import { Link } from "wouter";

const iconMap: Record<string, React.ElementType> = { HeartPulse, Utensils, Wrench, BriefcaseBusiness, Hotel, Building2 };
const categoryTones = ["bg-[#fff0f2] text-[#d44f68]", "bg-[#fff3e8] text-[#d46b38]", "bg-[#eaf6ff] text-[#287bb7]", "bg-[#edf1ff] text-[#4967d3]", "bg-[#f3efff] text-[#8057ca]", "bg-[#e9f9f4] text-[#17876f]"];

export default function Home() {
  const searchInput = useMemo(() => ({ query: "", offset: 0, limit: 3 }), []);
  const { data: featured, isLoading } = trpc.discovery.search.useQuery(searchInput);
  const { data: categories } = trpc.discovery.categories.useQuery();
  const cardItems = (featured?.items ?? []) as BusinessCardData[];
  return <PageFrame>
    <section className="overflow-hidden bg-[#f7f7f3] pb-16 pt-8 sm:pb-24 sm:pt-12">
      <div className="container">
        <div className="local-grid relative isolate overflow-hidden rounded-[34px] bg-[#0e1b3d] px-6 pb-14 pt-12 text-white shadow-[0_28px_80px_rgba(11,24,61,.27)] sm:px-12 sm:pb-20 sm:pt-20">
          <div className="signal-orb absolute -right-24 -top-28 size-[520px]" /><div className="absolute -bottom-44 left-[24%] size-[390px] rounded-full bg-[#d96b4b] opacity-25 blur-3xl" /><div className="absolute inset-x-[15%] bottom-0 h-px bg-gradient-to-r from-transparent via-blue-300/60 to-transparent" />
          <div className="relative mx-auto max-w-4xl text-center"><div className="mb-6 flex justify-center"><span className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3.5 py-1.5 text-xs font-semibold text-blue-100 backdrop-blur"><Compass className="size-3.5" />Local decisions, better informed</span></div><h1 className="mx-auto max-w-3xl text-balance text-4xl font-bold tracking-[-.065em] sm:text-6xl">Find the right local place.<br /><span className="text-[#a9c3ff]">Know what to do next.</span></h1><p className="mx-auto mt-5 max-w-xl text-pretty text-base leading-7 text-blue-100/80 sm:text-lg">Compare useful business information, see confidence signals, and act on the option that fits — all in one local search.</p></div>
          <div className="relative mt-9"><SearchHero /></div>
          <div className="relative mt-5 flex flex-wrap justify-center gap-2 text-xs font-medium text-blue-100/75"><span className="inline-flex items-center gap-1.5"><MapPinned className="size-3.5" />GPS-aware nearby discovery</span><span className="hidden sm:block">•</span><span>Independent Just Finds profiles</span><span className="hidden sm:block">•</span><span>Built for practical decisions</span></div>
        </div>
      </div>
    </section>
    <section className="py-14 sm:py-20"><div className="container"><div className="flex items-end justify-between gap-5"><div><p className="eyebrow">Explore with context</p><h2 className="section-title">Start with what you need.</h2><p className="mt-3 max-w-lg text-sm leading-6 text-slate-600">Each category brings forward the facts that matter for that type of decision — without making every local business fit the same template.</p></div><Link href="/search" className="hidden items-center gap-1 text-sm font-bold text-[#2559d6] sm:inline-flex">Browse all categories <ChevronRight className="size-4" /></Link></div><div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{(categories ?? []).slice(0, 6).map((category, index) => { const Icon = iconMap[category.icon] ?? Building2; return <Link href={`/search?category=${category.slug}`} key={category.slug} className="group rounded-[22px] border border-[#dce3ef] bg-white p-4 shadow-[0_10px_26px_rgba(14,27,61,.045)] transition-[transform,box-shadow,border-color] duration-200 hover:-translate-y-1 hover:border-[#b8c8f3] hover:shadow-[0_18px_32px_rgba(14,27,61,.09)]"><span className={`grid size-11 place-items-center rounded-2xl ${categoryTones[index]}`}><Icon className="size-5" /></span><p className="mt-4 text-sm font-bold tracking-[-.02em] text-[#162443]">{category.name}</p><p className="mt-1 line-clamp-2 text-xs leading-5 text-slate-500">{category.description ?? "Explore nearby"}</p><span className="mt-4 inline-flex items-center gap-1 text-xs font-bold text-[#2559d6] opacity-0 transition-opacity group-hover:opacity-100">Explore <ArrowRight className="size-3.5" /></span></Link>})}</div></div></section>
    <section className="border-y border-[#e6e9f0] bg-white py-14 sm:py-20"><div className="container"><div className="grid gap-8 lg:grid-cols-[1.25fr_.75fr]"><div><div className="flex items-end justify-between gap-5"><div><p className="eyebrow">Worth checking nearby</p><h2 className="section-title">Built for the next move.</h2></div><LocationPill /></div><div className="mt-7 grid gap-4">{isLoading ? [...Array(3)].map((_, index) => <div key={index} className="h-48 animate-pulse rounded-3xl bg-slate-100" />) : cardItems.map((item, index) => <BusinessCard item={item} imageIndex={index} key={item.id} />)}</div><Link href="/search" className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-[#2559d6]">See more nearby <ArrowRight className="size-4" /></Link></div><aside className="relative isolate overflow-hidden rounded-[28px] border border-[#dbe4f8] bg-[#eef3ff] p-6 shadow-[0_16px_34px_rgba(14,27,61,.07)] sm:p-8"><div className="absolute -right-12 top-24 size-52 rounded-full bg-[#9eb8ff] opacity-55 blur-3xl" /><div className="local-grid absolute inset-0 opacity-[.16]" /><div className="relative"><span className="grid size-11 place-items-center rounded-2xl bg-[#d96b4b] text-white shadow-[0_10px_18px_rgba(217,107,75,.24)]"><MapPinned className="size-5" /></span><h3 className="mt-6 text-2xl font-bold tracking-[-.045em] text-[#0e1b3d]">More than a pin on a map.</h3><p className="mt-4 text-sm leading-7 text-slate-600">Just Finds brings together category fit, location, verified information, profile completeness, availability, and relevant interactions — without pretending a single rating tells the whole story.</p><div className="mt-7 grid gap-3"><ScoreLine label="Category relevance" value="Matched" /><ScoreLine label="Distance awareness" value="GPS-ready" /><ScoreLine label="Profile confidence" value="Verified signals" /></div><Link href="/search" className="mt-8 inline-flex items-center gap-2 rounded-xl bg-[#0e1b3d] px-4 py-3 text-sm font-bold text-white shadow-[0_8px_18px_rgba(14,27,61,.18)] transition-transform active:scale-[.97]">Explore local places <ArrowRight className="size-4" /></Link></div></aside></div></div></section>
    <section className="py-14 sm:py-20"><div className="container"><div className="relative isolate overflow-hidden rounded-[30px] border border-[#cedaf7] bg-[#eaf0ff] px-6 py-9 shadow-[0_14px_32px_rgba(37,89,214,.06)] sm:px-10 sm:py-12"><div className="local-grid absolute inset-0 opacity-[.12]" /><div className="absolute inset-y-0 right-0 hidden w-[42%] bg-[linear-gradient(135deg,transparent_20%,rgba(37,89,214,.10)_20%,rgba(37,89,214,.10)_70%,transparent_70%)] lg:block" /><div className="relative grid gap-8 lg:grid-cols-[1fr_.75fr] lg:items-center"><div><p className="eyebrow">For local businesses</p><h2 className="mt-2 text-3xl font-bold tracking-[-.06em] text-[#0e1b3d] sm:text-4xl">Give customers a clearer reason to choose you.</h2><p className="mt-4 max-w-xl text-sm leading-7 text-slate-600">Manage accurate category details, leads, booking requests, your public website, and helpful AI-assisted content from one focused workspace.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/owner"><Button className="rounded-xl bg-[#2559d6] shadow-[0_10px_20px_rgba(37,89,214,.22)] hover:bg-[#1f4fc8]">List your business <ArrowRight className="ml-1 size-4" /></Button></Link><Link href="/owner"><Button variant="outline" className="rounded-xl border-[#c6d3f3] bg-white text-[#193b87] hover:bg-[#f7f9ff]">Owner workspace</Button></Link></div></div><div className="rounded-[22px] border border-white/90 bg-white/78 p-5 shadow-[0_16px_30px_rgba(23,61,156,.09)] backdrop-blur"><div className="flex items-center justify-between"><span className="text-sm font-bold text-[#182646]">Profile readiness</span><BadgeCheck className="size-5 text-[#2559d6]" /></div><div className="mt-5 h-2.5 overflow-hidden rounded-full bg-[#e6ebf5]"><div className="h-full w-[86%] rounded-full bg-[linear-gradient(90deg,#2559d6,#7798f5)]" /></div><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><MiniStat label="Business fields" value="Dynamic" /><MiniStat label="AI content" value="Approval-led" /><MiniStat label="Leads" value="Private" /><MiniStat label="Domains" value="Ready" /></div></div></div></div></div></section>
  </PageFrame>;
}
function ScoreLine({ label, value }: { label: string; value: string }) { return <div className="flex items-center justify-between rounded-xl border border-white/85 bg-white/78 px-3.5 py-3 text-sm shadow-sm"><span className="font-medium text-slate-600">{label}</span><span className="font-bold text-[#17284c]">{value}</span></div>; }
function MiniStat({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-[#edf0f7] bg-[#fbfcff] px-3 py-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 font-bold text-[#273a61]">{value}</p></div>; }
