import { PageFrame } from "@/components/PageFrame";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Sheet, SheetClose, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { trpc } from "@/lib/trpc";
import { getJobTypeLabel, hasJobFact, jobTypeOptions, type JobTypeFilter } from "@/lib/jobsPresentation";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { BriefcaseBusiness, Building2, ChevronRight, Clock3, FileText, MapPin, Search, SlidersHorizontal, X } from "lucide-react";
import { useMemo, useState, type Dispatch, type SetStateAction } from "react";

type JobsFilters = { city: string; jobType: JobTypeFilter };
type City = { name: string; slug: string };
type Job = { id: number; title: string; company: string | null; city: string | null; category: string; experience: string | null; salary: string | null; jobType: string; posted: Date | string | null };

export default function Jobs() {
  const [query, setQuery] = useState("");
  const [submittedQuery, setSubmittedQuery] = useState("");
  const [filters, setFilters] = useState<JobsFilters>({ city: "", jobType: "" });
  const [draftFilters, setDraftFilters] = useState<JobsFilters>({ city: "", jobType: "" });
  const { data: cities } = trpc.discovery.locations.useQuery();
  const input = useMemo(() => ({ query: submittedQuery, city: filters.city || undefined, jobType: filters.jobType || undefined }), [submittedQuery, filters.city, filters.jobType]);
  const { data: jobs, isLoading, isError, refetch } = trpc.jobs.list.useQuery(input);
  const activeFilterCount = Number(Boolean(filters.city)) + Number(Boolean(filters.jobType));
  const clearFilters = () => { setFilters({ city: "", jobType: "" }); setDraftFilters({ city: "", jobType: "" }); };

  return <PageFrame>
    <section className="border-b border-[var(--jf-border)] bg-[var(--jf-canvas)] py-8 sm:py-10"><div className="container"><div className="max-w-3xl"><p className="eyebrow"><BriefcaseBusiness className="mr-1.5 inline size-3.5" />Local jobs</p><h1 className="mt-3 text-3xl font-semibold tracking-[-.05em] text-[var(--jf-text)] sm:text-4xl">Explore real local roles.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[var(--jf-muted)]">Search currently published opportunities from local businesses. Details appear only when employers have provided them.</p></div>
      <form className="mt-7 flex max-w-4xl flex-col gap-2 rounded-2xl border border-[var(--jf-border)] bg-white p-2 shadow-[0_8px_24px_rgba(15,23,42,.05)] sm:flex-row" onSubmit={event => { event.preventDefault(); setSubmittedQuery(query); }}><label className="flex min-w-0 flex-1 items-center gap-3 rounded-xl px-3 py-1 focus-within:bg-slate-50"><Search className="size-5 shrink-0 text-[var(--jf-primary)]" /><span className="sr-only">Search jobs by role or title</span><Input value={query} onChange={event => setQuery(event.target.value)} placeholder="Role, title, or category" className="h-11 border-0 p-0 text-[var(--jf-text)] shadow-none focus-visible:ring-0" /></label><Button type="submit" className="h-11 rounded-xl px-5">Search jobs <ChevronRight className="ml-1.5 size-4" /></Button></form>
    </div></section>
    <section className="container py-7 pb-28 sm:py-10 sm:pb-12"><div className="flex items-end justify-between gap-4"><div><p className="eyebrow">Job discovery</p><h2 className="mt-1 text-xl font-semibold tracking-[-.03em] text-[var(--jf-text)]">Published opportunities</h2><p className="mt-1.5 text-sm text-[var(--jf-muted)]">{isLoading ? "Loading roles…" : `${jobs?.length ?? 0} ${jobs?.length === 1 ? "role" : "roles"} found`}</p></div><div className="md:hidden"><MobileFilters cities={cities ?? []} filters={draftFilters} onChange={setDraftFilters} activeCount={activeFilterCount} onApply={() => setFilters(draftFilters)} onClear={clearFilters} /></div></div>
      <div className="mt-6 grid gap-7 md:grid-cols-[230px_minmax(0,1fr)] lg:grid-cols-[250px_minmax(0,1fr)]"><aside className="hidden h-fit rounded-2xl border border-[var(--jf-border)] bg-white p-5 md:block"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold text-[var(--jf-text)]">Filters</h3>{activeFilterCount > 0 && <button type="button" onClick={clearFilters} className="text-xs font-semibold text-[var(--jf-primary)] hover:underline">Clear</button>}</div><JobFilterFields cities={cities ?? []} filters={filters} onChange={setFilters} /></aside>
        <div className="min-w-0">{activeFilterCount > 0 && <div className="mb-4 flex flex-wrap items-center gap-2" aria-label="Applied job filters">{filters.city && <FilterChip label={cities?.find(city => city.slug === filters.city)?.name ?? filters.city} onRemove={() => setFilters(current => ({ ...current, city: "" }))} />}{filters.jobType && <FilterChip label={getJobTypeLabel(filters.jobType)} onRemove={() => setFilters(current => ({ ...current, jobType: "" }))} />}</div>}{isLoading ? <JobSkeletons /> : isError ? <div className="rounded-2xl border border-rose-200 bg-rose-50 p-7"><h3 className="font-semibold text-rose-950">Jobs could not be loaded.</h3><p className="mt-2 text-sm leading-6 text-rose-800">Your search and filters are still available. Try again to refresh current published roles.</p><Button type="button" variant="outline" onClick={() => refetch()} className="mt-4 border-rose-200 bg-white text-rose-800">Try again</Button></div> : jobs?.length ? <div className="grid gap-3">{jobs.map(job => <JobCard key={job.id} job={job} />)}</div> : <EmptyJobs hasFilters={Boolean(submittedQuery || activeFilterCount)} onClear={clearFilters} />}</div>
      </div></section>
  </PageFrame>;
}

function JobFilterFields({ cities, filters, onChange }: { cities: City[]; filters: JobsFilters; onChange: Dispatch<SetStateAction<JobsFilters>> }) {
  return <div className="mt-5 grid gap-5"><label className="grid gap-2 text-sm font-medium text-slate-700">City<select value={filters.city} onChange={event => onChange(current => ({ ...current, city: event.target.value }))} className="h-11 w-full rounded-xl border border-[var(--jf-border)] bg-white px-3 text-sm font-normal text-[var(--jf-text)] outline-none transition-colors focus:border-[var(--jf-primary)] focus:ring-2 focus:ring-blue-100"><option value="">All approved cities</option>{cities.map(city => <option key={city.slug} value={city.slug}>{city.name}</option>)}</select></label><label className="grid gap-2 text-sm font-medium text-slate-700">Employment type<select value={filters.jobType} onChange={event => onChange(current => ({ ...current, jobType: event.target.value as JobTypeFilter }))} className="h-11 w-full rounded-xl border border-[var(--jf-border)] bg-white px-3 text-sm font-normal text-[var(--jf-text)] outline-none transition-colors focus:border-[var(--jf-primary)] focus:ring-2 focus:ring-blue-100"><option value="">All job types</option>{jobTypeOptions.map(option => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label></div>;
}

function MobileFilters({ cities, filters, onChange, activeCount, onApply, onClear }: { cities: City[]; filters: JobsFilters; onChange: Dispatch<SetStateAction<JobsFilters>>; activeCount: number; onApply: () => void; onClear: () => void }) {
  return <Sheet><SheetTrigger asChild><Button variant="outline" className="h-11 border-[var(--jf-border)] bg-white"><SlidersHorizontal className="mr-2 size-4" />Filters{activeCount > 0 && <span className="ml-2 grid size-5 place-items-center rounded-full bg-blue-100 text-[10px] font-bold text-[var(--jf-primary)]">{activeCount}</span>}</Button></SheetTrigger><SheetContent side="bottom" className="rounded-t-3xl border-[var(--jf-border)] bg-white pb-[max(1rem,env(safe-area-inset-bottom))]"><SheetHeader className="px-5 pt-5"><SheetTitle>Filter jobs</SheetTitle><SheetDescription>Limit published jobs by approved city or employment type.</SheetDescription></SheetHeader><div className="px-5"><JobFilterFields cities={cities} filters={filters} onChange={onChange} /></div><SheetFooter className="mt-6 grid grid-cols-2 gap-3 px-5"><Button type="button" variant="outline" onClick={onClear}>Clear</Button><SheetClose asChild><Button type="button" onClick={onApply}>Show jobs</Button></SheetClose></SheetFooter></SheetContent></Sheet>;
}

function FilterChip({ label, onRemove }: { label: string; onRemove: () => void }) { return <span className="inline-flex items-center gap-1.5 rounded-full border border-blue-100 bg-blue-50 px-3 py-1.5 text-xs font-semibold text-blue-800">{label}<button type="button" onClick={onRemove} aria-label={`Remove ${label} filter`} className="rounded-full p-0.5 hover:bg-blue-100"><X className="size-3" /></button></span>; }

function JobCard({ job }: { job: Job }) { return <article className="rounded-2xl border border-[var(--jf-border)] bg-white p-5 transition-shadow duration-200 hover:shadow-[0_10px_24px_rgba(15,23,42,.06)]"><div className="flex gap-4"><div className="grid size-11 shrink-0 place-items-center rounded-xl bg-blue-50 text-[var(--jf-primary)]"><BriefcaseBusiness className="size-5" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-lg font-semibold tracking-[-.025em] text-[var(--jf-text)]">{job.title}</h3>{hasJobFact(job.company) && <p className="mt-1 text-sm text-[var(--jf-muted)]">{job.company}</p>}</div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-semibold text-slate-700">{getJobTypeLabel(job.jobType)}</span></div><div className="mt-4 flex flex-wrap gap-x-4 gap-y-2 text-xs text-[var(--jf-muted)]"><span className="inline-flex items-center gap-1"><Building2 className="size-3.5" />{job.category}</span>{hasJobFact(job.city) && <span className="inline-flex items-center gap-1"><MapPin className="size-3.5" />{job.city}</span>}{hasJobFact(job.experience) && <span className="inline-flex items-center gap-1"><Clock3 className="size-3.5" />{job.experience}</span>}{hasJobFact(job.salary) && <span>{job.salary}</span>}</div><div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-4">{job.posted ? <span className="text-xs text-slate-400">Published {formatPublishedDate(job.posted)}</span> : <span />}<JobApplyDialog jobId={job.id} title={job.title} /></div></div></div></article>; }

function formatPublishedDate(value: Date | string) { return new Intl.DateTimeFormat(undefined, { day: "numeric", month: "short", year: "numeric" }).format(new Date(value)); }
function JobSkeletons() { return <div className="grid gap-3" aria-label="Loading jobs">{[0, 1, 2].map(index => <div key={index} className="h-44 animate-pulse rounded-2xl border border-slate-100 bg-slate-50" />)}</div>; }
function EmptyJobs({ hasFilters, onClear }: { hasFilters: boolean; onClear: () => void }) { return <div className="rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-8 text-center sm:p-10"><FileText className="mx-auto size-8 text-slate-400" /><h3 className="mt-3 font-semibold text-[var(--jf-text)]">{hasFilters ? "No published jobs match this search." : "No published jobs are available right now."}</h3><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-[var(--jf-muted)]">{hasFilters ? "Try a broader role search or remove a filter to explore other current opportunities." : "New local roles appear here once employers publish them through Just Finds."}</p>{hasFilters && <Button type="button" variant="outline" onClick={onClear} className="mt-5 bg-white">Clear filters</Button>}</div>; }
function JobApplyDialog({ jobId, title }: { jobId: number; title: string }) { const { isAuthenticated } = useAuth(); const [note, setNote] = useState(""); const apply = trpc.jobs.submitApplication.useMutation(); return <Dialog><DialogTrigger asChild><Button variant="outline" className="h-10 bg-white text-xs">View role <ChevronRight className="ml-1 size-3.5" /></Button></DialogTrigger><DialogContent className="rounded-2xl"><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>Applications are private to the employer and are available only for approved published roles.</DialogDescription></DialogHeader>{!isAuthenticated ? <div className="rounded-xl bg-slate-50 p-5"><p className="text-sm leading-6 text-slate-600">Sign in to apply and keep a private record of your local job applications.</p><Button onClick={() => startLogin()} className="mt-4">Sign in to apply</Button></div> : <div className="grid gap-3"><label className="text-sm font-semibold text-slate-700">Message to employer<textarea value={note} onChange={event => setNote(event.target.value)} placeholder="Briefly introduce yourself and your relevant experience." className="mt-2 min-h-28 w-full rounded-xl border border-slate-200 p-3 text-sm font-normal outline-none focus:border-blue-400" /></label><Button disabled={apply.isPending || apply.isSuccess} onClick={() => apply.mutate({ jobId, note: note || undefined })}>{apply.isSuccess ? "Application submitted" : apply.isPending ? "Submitting…" : "Submit application"}</Button>{apply.error && <p className="rounded-lg bg-rose-50 p-3 text-xs leading-5 text-rose-700">{apply.error.message}</p>}</div>}</DialogContent></Dialog>; }
