export const demoCategories = [
  { id: 1, name: "Healthcare", slug: "healthcare", icon: "HeartPulse", description: "Clinics, wellness, diagnostics, and care." },
  { id: 2, name: "Food & Dining", slug: "food", icon: "Utensils", description: "Restaurants, cafés, bakeries, and more." },
  { id: 3, name: "Home Services", slug: "home-services", icon: "Wrench", description: "Trusted specialists for your home." },
  { id: 4, name: "Education", slug: "education", icon: "GraduationCap", description: "Learning, coaching, and training." },
  { id: 5, name: "Hotels & Stays", slug: "stays", icon: "BedDouble", description: "Stays for every kind of trip." },
  { id: 6, name: "Professional", slug: "professional", icon: "BriefcaseBusiness", description: "Local experts and services." },
] as const;

export const demoBusinesses = [
  {
    id: 101,
    name: "Aarohan Wellness Clinic",
    slug: "aarohan-wellness-clinic",
    category: "Healthcare",
    categorySlug: "healthcare",
    city: "Kanpur",
    citySlug: "kanpur",
    locality: "Swaroop Nagar",
    address: "Swaroop Nagar, Kanpur, Uttar Pradesh",
    shortDescription: "A calm, appointment-led wellness clinic with a profile built for clear information and easy contact.",
    latitude: 26.4767,
    longitude: 80.3188,
    verified: true,
    profileCompleteness: 94,
    recommendationScore: 88,
    reputationScore: 91,
    openNow: true,
    services: ["Consultation requests", "Wellness plans", "Appointment support"],
    hours: ["Mon–Sat: 09:00–19:00", "Sun: Closed"],
    phone: "+91 512 555 0198",
    whatsapp: "+91 512 555 0198",
    website: "https://example.com",
  },
  {
    id: 102,
    name: "Saffron Table Kitchen",
    slug: "saffron-table-kitchen",
    category: "Food & Dining",
    categorySlug: "food",
    city: "Kanpur",
    citySlug: "kanpur",
    locality: "Civil Lines",
    address: "Civil Lines, Kanpur, Uttar Pradesh",
    shortDescription: "A contemporary neighbourhood kitchen for everyday dining, direct contact, and directions.",
    latitude: 26.4598,
    longitude: 80.3319,
    verified: true,
    profileCompleteness: 90,
    recommendationScore: 84,
    reputationScore: 87,
    openNow: true,
    services: ["Dine-in", "Takeaway", "Group bookings"],
    hours: ["Daily: 12:00–23:00"],
    phone: "+91 512 555 0125",
    whatsapp: "+91 512 555 0125",
    website: "https://example.com",
  },
  {
    id: 103,
    name: "Northern Star Learning Studio",
    slug: "northern-star-learning-studio",
    category: "Education",
    categorySlug: "education",
    city: "Kanpur",
    citySlug: "kanpur",
    locality: "Kakadeo",
    address: "Kakadeo, Kanpur, Uttar Pradesh",
    shortDescription: "A structured local learning studio with programme information, enquiry capture, and clear schedules.",
    latitude: 26.4812,
    longitude: 80.3033,
    verified: false,
    profileCompleteness: 82,
    recommendationScore: 76,
    reputationScore: 78,
    openNow: false,
    services: ["Foundation programmes", "Small batches", "Mentor sessions"],
    hours: ["Mon–Sat: 10:00–18:00", "Sun: Closed"],
    phone: "+91 512 555 0122",
    whatsapp: "+91 512 555 0122",
    website: "https://example.com",
  },
] as const;

export const demoJobs = [
  { id: 201, title: "Client Experience Coordinator", company: "Aarohan Wellness Clinic", city: "Kanpur", category: "Healthcare", experience: "1–3 years", salary: "Discuss on enquiry", jobType: "Full-time", posted: "Recently added" },
  { id: 202, title: "Kitchen Operations Lead", company: "Saffron Table Kitchen", city: "Kanpur", category: "Food & Dining", experience: "2–4 years", salary: "Discuss on enquiry", jobType: "Full-time", posted: "Recently added" },
  { id: 203, title: "Learning Advisor", company: "Northern Star Learning Studio", city: "Kanpur", category: "Education", experience: "0–2 years", salary: "Discuss on enquiry", jobType: "Part-time", posted: "Recently added" },
] as const;
