import { BadgeCheck, ChevronRight, Clock3, Compass, ExternalLink, MapPin, MessageCircle, Phone, ShieldCheck } from "lucide-react";
import { Link } from "wouter";

export type BusinessCardData = {
  id: number; name: string; slug: string; category: string; categorySlug: string; city: string; citySlug: string; locality: string; address: string; shortDescription: string; verified: boolean; openNow: boolean; distanceKm: number | null; reputationScore: number; reviewSummary: string; phone?: string; whatsapp?: string;
};

export function BusinessCard({ item, imageIndex = 0 }: { item: BusinessCardData; imageIndex?: number }) {
  const imageUrls = ["/manus-storage/restaurant-interior_5cce32e4.jpg", "/manus-storage/storefront_08732e8f.jpg", "/manus-storage/retail-interior_7d7388ed.jpg"];
  return <article className="group overflow-hidden rounded-[22px] border border-slate-200 bg-white p-3 shadow-[0_10px_30px_rgba(15,23,42,.045)] transition-[transform,box-shadow] duration-200 hover:-translate-y-0.5 hover:shadow-[0_16px_35px_rgba(15,23,42,.10)] sm:flex sm:gap-4">
    <div className="relative h-40 overflow-hidden rounded-[16px] bg-slate-100 sm:h-auto sm:w-44 sm:shrink-0"><img src={imageUrls[imageIndex % imageUrls.length]} alt="" className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105" /><span className="absolute left-2.5 top-2.5 rounded-full bg-white/92 px-2.5 py-1 text-[10px] font-semibold text-slate-700 backdrop-blur">{item.category}</span></div>
    <div className="flex min-w-0 flex-1 flex-col px-1 pt-3 sm:px-0 sm:pt-1">
      <div className="flex items-start justify-between gap-3"><div><Link href={`/${item.categorySlug}/${item.citySlug}/${item.slug}`} className="inline-flex items-center gap-1.5 text-[17px] font-semibold tracking-[-.025em] text-slate-950 hover:text-[#1f51c8]">{item.name}{item.verified && <BadgeCheck className="size-4 text-[#1f51c8]" aria-label="Verified listing" />}</Link><p className="mt-1 text-sm text-slate-500">{item.locality}, {item.city}</p></div><ChevronRight className="mt-1 size-5 shrink-0 text-slate-300" /></div>
      <p className="mt-3 line-clamp-2 text-sm leading-6 text-slate-600">{item.shortDescription}</p>
      <div className="mt-4 flex flex-wrap gap-2 text-xs"><span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 font-medium ${item.openNow ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600"}`}><Clock3 className="size-3.5" />{item.openNow ? "Open now" : "Hours available"}</span>{item.distanceKm !== null && <span className="inline-flex items-center gap-1 rounded-full bg-slate-100 px-2.5 py-1 font-medium text-slate-600"><Compass className="size-3.5" />{item.distanceKm.toFixed(1)} km away</span>}<span className="inline-flex items-center gap-1 rounded-full bg-indigo-50 px-2.5 py-1 font-medium text-indigo-700"><ShieldCheck className="size-3.5" />Score {item.reputationScore}</span></div>
      <div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-3"><span className="text-xs text-slate-400">{item.reviewSummary}</span><div className="flex gap-1">{item.phone && <a href={`tel:${item.phone}`} className="grid size-8 place-items-center rounded-lg text-slate-600 hover:bg-blue-50 hover:text-[#1f51c8]" aria-label={`Call ${item.name}`}><Phone className="size-4" /></a>}{item.whatsapp && <a href={`https://wa.me/${item.whatsapp.replace(/\D/g, "")}`} target="_blank" rel="noreferrer" className="grid size-8 place-items-center rounded-lg text-slate-600 hover:bg-emerald-50 hover:text-emerald-700" aria-label={`Message ${item.name}`}><MessageCircle className="size-4" /></a>}<a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(item.address)}`} target="_blank" rel="noreferrer" className="grid size-8 place-items-center rounded-lg text-slate-600 hover:bg-orange-50 hover:text-orange-700" aria-label={`Directions to ${item.name}`}><MapPin className="size-4" /></a><Link href={`/${item.categorySlug}/${item.citySlug}/${item.slug}`} className="grid size-8 place-items-center rounded-lg text-slate-600 hover:bg-slate-100" aria-label={`View ${item.name}`}><ExternalLink className="size-4" /></Link></div></div>
    </div>
  </article>;
}
