import { BadgeCheck, ChevronRight, Clock3, Compass, ExternalLink, MapPin, MessageCircle, Phone, ShieldCheck } from "lucide-react";
import { Link } from "wouter";

export type BusinessCardData = {
  id: number; name: string; slug: string; category: string; categorySlug: string; city: string; citySlug: string; locality: string; address: string; shortDescription: string; verified: boolean; openNow: boolean; distanceKm: number | null; reputationScore: number; reviewSummary: string; phone?: string; whatsapp?: string;
};

export function BusinessCard({ item, imageIndex = 0, onInteraction }: { item: BusinessCardData; imageIndex?: number; onInteraction?: (businessId: number, action: "click" | "call" | "whatsapp" | "directions" | "website") => void }) {
  const imageUrls = ["/manus-storage/restaurant-interior_5cce32e4.jpg", "/manus-storage/storefront_08732e8f.jpg", "/manus-storage/retail-interior_7d7388ed.jpg"];
  return <article className="group overflow-hidden rounded-[26px] border border-[#dce3ef] bg-white p-3.5 shadow-[0_14px_34px_rgba(14,27,61,.055)] transition-[transform,box-shadow,border-color] duration-200 hover:-translate-y-1 hover:border-[#b8c8f3] hover:shadow-[0_20px_44px_rgba(14,27,61,.11)] sm:flex sm:gap-5">
    <div className="relative h-44 overflow-hidden rounded-[19px] bg-slate-100 sm:h-auto sm:w-48 sm:shrink-0"><img src={imageUrls[imageIndex % imageUrls.length]} alt="" className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105" /><div className="absolute inset-x-0 bottom-0 h-16 bg-gradient-to-t from-[#0e1b3d]/48 to-transparent" /><span className="absolute left-2.5 top-2.5 rounded-full border border-white/55 bg-white/90 px-2.5 py-1 text-[10px] font-bold tracking-[.04em] text-[#243a67] backdrop-blur">{item.category}</span></div>
    <div className="flex min-w-0 flex-1 flex-col px-1 pt-3 sm:px-0 sm:pt-1">
      <div className="flex items-start justify-between gap-3"><div><Link href={`/${item.categorySlug}/${item.citySlug}/${item.slug}`} onClick={() => onInteraction?.(item.id, "click")} className="inline-flex items-center gap-1.5 text-[17px] font-bold tracking-[-.035em] text-[#0e1b3d] hover:text-[#2559d6]">{item.name}{item.verified && <BadgeCheck className="size-4 text-[#2559d6]" aria-label="Verified listing" />}</Link><p className="mt-1 text-sm font-medium text-slate-500">{item.locality}, {item.city}</p></div><span className="grid size-8 shrink-0 place-items-center rounded-full bg-[#f2f5fc] text-[#5473bf] transition-colors group-hover:bg-[#2559d6] group-hover:text-white"><ChevronRight className="size-4" /></span></div>
      <p className="mt-3 line-clamp-2 text-sm leading-6 text-slate-600">{item.shortDescription}</p>
      <div className="mt-4 flex flex-wrap gap-2 text-xs"><span className={`inline-flex items-center gap-1 rounded-full border px-2.5 py-1 font-semibold ${item.openNow ? "border-emerald-100 bg-emerald-50 text-emerald-700" : "border-slate-200 bg-slate-50 text-slate-600"}`}><Clock3 className="size-3.5" />{item.openNow ? "Open now" : "Hours available"}</span>{item.distanceKm !== null && <span className="inline-flex items-center gap-1 rounded-full border border-slate-200 bg-slate-50 px-2.5 py-1 font-semibold text-slate-600"><Compass className="size-3.5" />{item.distanceKm.toFixed(1)} km away</span>}<span className="inline-flex items-center gap-1 rounded-full border border-[#d8e2ff] bg-[#f3f6ff] px-2.5 py-1 font-semibold text-[#3158ae]"><ShieldCheck className="size-3.5" />Score {item.reputationScore}</span></div>
      <div className="mt-4 flex items-center justify-between border-t border-[#edf0f6] pt-3"><span className="text-xs text-slate-400">{item.reviewSummary}</span><div className="flex gap-1">{item.phone && <a href={`tel:${item.phone}`} onClick={() => onInteraction?.(item.id, "call")} className="grid size-8 place-items-center rounded-lg text-slate-600 hover:bg-blue-50 hover:text-[#2559d6]" aria-label={`Call ${item.name}`}><Phone className="size-4" /></a>}{item.whatsapp && <a href={`https://wa.me/${item.whatsapp.replace(/\D/g, "")}`} onClick={() => onInteraction?.(item.id, "whatsapp")} target="_blank" rel="noreferrer" className="grid size-8 place-items-center rounded-lg text-slate-600 hover:bg-emerald-50 hover:text-emerald-700" aria-label={`Message ${item.name}`}><MessageCircle className="size-4" /></a>}<a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(item.address)}`} onClick={() => onInteraction?.(item.id, "directions")} target="_blank" rel="noreferrer" className="grid size-8 place-items-center rounded-lg text-slate-600 hover:bg-orange-50 hover:text-orange-700" aria-label={`Directions to ${item.name}`}><MapPin className="size-4" /></a><Link href={`/${item.categorySlug}/${item.citySlug}/${item.slug}`} onClick={() => onInteraction?.(item.id, "click")} className="grid size-8 place-items-center rounded-lg text-slate-600 hover:bg-slate-100" aria-label={`View ${item.name}`}><ExternalLink className="size-4" /></Link></div></div>
    </div>
  </article>;
}
