import { formatDistance } from "@/hooks/useUserLocation";
import { BadgeCheck, Building2, ChevronRight, Clock3, Compass, ExternalLink, MapPin, MessageCircle, Phone } from "lucide-react";
import { Link } from "wouter";
import { StatusBadge } from "./ProductPrimitives";

export type BusinessCardData = {
  id: number; name: string; slug: string; category: string; categorySlug: string; city: string; citySlug: string; locality: string; address: string; shortDescription: string; verified: boolean; openNow: boolean; distanceKm: number | null; reputationScore: number; reviewSummary: string; phone?: string; whatsapp?: string;
};

export function BusinessCard({ item, onInteraction }: { item: BusinessCardData; imageIndex?: number; onInteraction?: (businessId: number, action: "click" | "call" | "whatsapp" | "directions" | "website") => void }) {
  const profileHref = `/${item.categorySlug}/${item.citySlug}/${item.slug}`;
  const locality = [item.locality, item.city].filter(Boolean).join(", ");
  return <article className="jf-card jf-card-interactive group flex min-h-[208px] flex-col rounded-[22px] p-4 sm:p-5">
    <div className="flex items-start gap-3.5">
      <span className="grid size-12 shrink-0 place-items-center rounded-2xl border border-blue-100 bg-blue-50 text-[var(--jf-primary)]"><Building2 className="size-5" /></span>
      <div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-[11px] font-bold uppercase tracking-[.11em] text-[var(--jf-primary)]">{item.category}</p><Link href={profileHref} onClick={() => onInteraction?.(item.id, "click")} className="mt-1 inline-flex max-w-full items-center gap-1.5 text-[17px] font-bold tracking-[-.035em] text-[var(--jf-text)] hover:text-[var(--jf-primary)]"><span className="truncate">{item.name}</span>{item.verified && <BadgeCheck className="size-4 shrink-0 text-[var(--jf-primary)]" aria-label="Verified listing" />}</Link></div><Link href={profileHref} onClick={() => onInteraction?.(item.id, "click")} className="grid size-9 shrink-0 place-items-center rounded-xl border border-[var(--jf-border)] text-[var(--jf-muted)] transition-colors hover:border-blue-200 hover:bg-blue-50 hover:text-[var(--jf-primary)]" aria-label={`View ${item.name}`}><ChevronRight className="size-4" /></Link></div><p className="mt-1.5 flex items-center gap-1.5 text-sm text-[var(--jf-muted)]"><MapPin className="size-3.5 shrink-0 text-[var(--jf-warm)]" /><span className="truncate">{locality || "Location available on profile"}</span></p></div>
    </div>
    {item.shortDescription && <p className="mt-4 line-clamp-2 text-sm leading-6 text-slate-600">{item.shortDescription}</p>}
    <div className="mt-4 flex flex-wrap gap-2 text-xs"><StatusBadge label={item.openNow ? "Open now" : "Hours available"} tone={item.openNow ? "positive" : "neutral"} icon={Clock3} />{formatDistance(item.distanceKm) && <StatusBadge label={formatDistance(item.distanceKm)!} icon={Compass} />}{item.verified && <StatusBadge label="Verified" tone="info" icon={BadgeCheck} />}</div>
    <div className="mt-auto flex items-center justify-between border-t border-slate-100 pt-3.5"><Link href={profileHref} onClick={() => onInteraction?.(item.id, "click")} className="inline-flex items-center gap-1.5 text-sm font-bold text-[var(--jf-primary)]">View profile <ExternalLink className="size-3.5" /></Link><div className="flex gap-1">{item.phone && <a href={`tel:${item.phone}`} onClick={() => onInteraction?.(item.id, "call")} className="grid size-8 place-items-center rounded-lg text-slate-600 hover:bg-blue-50 hover:text-[var(--jf-primary)]" aria-label={`Call ${item.name}`}><Phone className="size-4" /></a>}{item.whatsapp && <a href={`https://wa.me/${item.whatsapp.replace(/\D/g, "")}`} onClick={() => onInteraction?.(item.id, "whatsapp")} target="_blank" rel="noreferrer" className="grid size-8 place-items-center rounded-lg text-slate-600 hover:bg-emerald-50 hover:text-emerald-700" aria-label={`Message ${item.name}`}><MessageCircle className="size-4" /></a>}<a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(item.address)}`} onClick={() => onInteraction?.(item.id, "directions")} target="_blank" rel="noreferrer" className="grid size-8 place-items-center rounded-lg text-slate-600 hover:bg-orange-50 hover:text-orange-700" aria-label={`Directions to ${item.name}`}><MapPin className="size-4" /></a></div></div>
  </article>;
}
