import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, CircleOff, Edit3, Info, ListTree, Loader2, LockKeyhole, MapPinned, MapPin, Plus, Search, ShieldCheck } from "lucide-react";
import React, { useMemo, useState } from "react";

type CategoryDraft = { id: number; name: string; description: string; icon: string; isActive: boolean };
type CityAction = { cityId: number; name: string; isActive: boolean };

function fieldLabel(value: string) { return value.replaceAll("_", " ").replace(/\b\w/g, letter => letter.toUpperCase()); }
function slugFor(value: string) { return value.trim().toLocaleLowerCase("en-IN").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, ""); }

export function GovernanceCatalogManager({ role }: { role?: string }) {
  const isSuperAdmin = role === "super_admin";
  const utils = trpc.useUtils();
  const catalogue = trpc.workspace.governanceCatalog.useQuery();
  const [scope, setScope] = useState<"categories" | "cities">("categories");
  const [query, setQuery] = useState("");
  const [tier, setTier] = useState<"all" | "tier1" | "tier2">("all");
  const [newCategoryOpen, setNewCategoryOpen] = useState(false);
  const [newCategory, setNewCategory] = useState({ name: "", description: "", icon: "Sparkles" });
  const [editingCategory, setEditingCategory] = useState<CategoryDraft | null>(null);
  const [pendingCity, setPendingCity] = useState<CityAction | null>(null);
  const [fieldDraft, setFieldDraft] = useState({ categoryId: "", fieldKey: "", label: "", fieldType: "text" });
  const invalidate = () => { void utils.workspace.governanceCatalog.invalidate(); void utils.workspace.categorySchemas.invalidate(); void utils.discovery.categories.invalidate(); void utils.discovery.locations.invalidate(); };
  const createCategory = trpc.workspace.createCategory.useMutation({ onSuccess: () => { invalidate(); setNewCategoryOpen(false); setNewCategory({ name: "", description: "", icon: "Sparkles" }); } });
  const updateCategory = trpc.workspace.updateCategoryGovernance.useMutation({ onSuccess: () => { invalidate(); setEditingCategory(null); } });
  const createCity = trpc.workspace.createCity.useMutation({ onSuccess: () => { invalidate(); setPendingCity(null); } });
  const setCityActive = trpc.workspace.setCityActive.useMutation({ onSuccess: () => { invalidate(); setPendingCity(null); } });
  const createField = trpc.workspace.createCategoryField.useMutation({ onSuccess: () => { invalidate(); setFieldDraft({ categoryId: "", fieldKey: "", label: "", fieldType: "text" }); } });
  const categories = useMemo(() => (catalogue.data?.categories ?? []).filter(category => `${category.name} ${category.slug} ${category.description ?? ""} ${category.icon}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())), [catalogue.data?.categories, query]);
  const cities = useMemo(() => (catalogue.data?.cities ?? []).filter(city => (tier === "all" || city.tier === tier) && `${city.name} ${city.state} ${city.slug}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())), [catalogue.data?.cities, query, tier]);
  const activeCategories = catalogue.data?.categories.filter(category => category.isActive && category.status === "active").length ?? 0;
  const activeCities = catalogue.data?.cities.filter(city => city.isActive).length ?? 0;

  return <section className="mt-7 space-y-5" aria-label="Category and city governance">
    <section className="overflow-hidden rounded-[24px] border border-slate-200 bg-white shadow-sm">
      <div className="flex flex-col gap-4 border-b border-slate-100 px-5 py-5 lg:flex-row lg:items-center lg:justify-between">
        <div className="flex items-start gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-indigo-50 text-indigo-700"><ListTree className="size-5" /></span><div><p className="text-sm font-bold text-slate-950">Controlled directory governance</p><p className="mt-1 max-w-2xl text-xs leading-5 text-slate-500">Taxonomy and city coverage are managed records. Only a super administrator can change availability or metadata; all other administrators retain a factual view.</p></div></div>
        <div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-slate-100 px-3 py-1.5 text-[11px] font-bold text-slate-700">{activeCategories} active categories</span><span className="rounded-full bg-indigo-50 px-3 py-1.5 text-[11px] font-bold text-indigo-800">{activeCities} active curated cities</span>{isSuperAdmin ? <Button className="h-9 rounded-xl bg-indigo-700 text-xs hover:bg-indigo-800" onClick={() => setNewCategoryOpen(true)}><Plus className="mr-1.5 size-4" />Add category</Button> : <span className="inline-flex items-center gap-1.5 rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-[11px] font-semibold text-slate-600"><LockKeyhole className="size-3.5" />View-only administrator</span>}</div>
      </div>
      {!isSuperAdmin && <div className="flex items-start gap-2 border-b border-amber-100 bg-amber-50 px-5 py-3 text-xs leading-5 text-amber-950"><LockKeyhole className="mt-0.5 size-4 shrink-0" /><span><strong>Super-administrator access is required</strong> to change category metadata, activation, field schema, or city availability.</span></div>}
      <div className="flex flex-col gap-3 px-5 py-4 md:flex-row md:items-center md:justify-between"><div className="inline-flex w-full rounded-xl bg-slate-100 p-1 md:w-auto"><button onClick={() => setScope("categories")} className={`h-8 flex-1 rounded-lg px-3 text-xs font-bold transition-colors md:flex-none ${scope === "categories" ? "bg-white text-slate-950 shadow-sm" : "text-slate-500 hover:text-slate-800"}`}>Categories</button><button onClick={() => setScope("cities")} className={`h-8 flex-1 rounded-lg px-3 text-xs font-bold transition-colors md:flex-none ${scope === "cities" ? "bg-white text-slate-950 shadow-sm" : "text-slate-500 hover:text-slate-800"}`}>India city catalogue</button></div><div className="flex w-full flex-col gap-2 sm:flex-row md:w-auto"><label className="relative block"><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400" /><input aria-label={`Search ${scope === "categories" ? "categories" : "cities"}`} value={query} onChange={event => setQuery(event.target.value)} placeholder={scope === "categories" ? "Search category or metadata" : "Search city or state"} className="h-10 w-full rounded-xl border border-slate-200 bg-white pl-9 pr-3 text-xs text-slate-800 outline-none transition focus:border-indigo-400 focus:ring-2 focus:ring-indigo-100 sm:w-64" /></label>{scope === "cities" && <select aria-label="Filter city tier" value={tier} onChange={event => setTier(event.target.value as typeof tier)} className="h-10 rounded-xl border border-slate-200 bg-white px-3 text-xs font-semibold text-slate-700 outline-none focus:border-indigo-400"><option value="all">All tiers</option><option value="tier1">Tier 1</option><option value="tier2">Tier 2</option></select>}</div></div>
      {catalogue.isLoading ? <div className="grid min-h-72 place-items-center text-sm text-slate-500"><span className="inline-flex items-center gap-2"><Loader2 className="size-4 animate-spin" />Loading governance catalogue…</span></div> : catalogue.error ? <div className="m-5 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800" role="alert">{catalogue.error.message}</div> : scope === "categories" ? <CategoryTable categories={categories} isSuperAdmin={isSuperAdmin} onEdit={category => setEditingCategory({ id: category.id, name: category.name, description: category.description ?? "", icon: category.icon, isActive: category.isActive })} /> : <CityTable cities={cities} isSuperAdmin={isSuperAdmin} onAction={action => setPendingCity(action)} />}
    </section>

    {scope === "categories" && <section className="rounded-[24px] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm font-bold text-slate-950">Category field schema</p><p className="mt-1 text-xs leading-5 text-slate-500">Fields are scoped to a category and appear in its owner workflow. This does not alter core listing facts.</p></div><span className="inline-flex items-center gap-1.5 text-[11px] font-semibold text-slate-500"><ShieldCheck className="size-3.5 text-indigo-700" />Category-scoped configuration</span></div>{isSuperAdmin ? <div className="mt-4 grid gap-2 md:grid-cols-[1.2fr_1fr_1fr_1fr_auto]"><select aria-label="Field category" value={fieldDraft.categoryId} onChange={event => setFieldDraft(current => ({ ...current, categoryId: event.target.value }))} className="h-10 rounded-xl border border-slate-200 bg-white px-3 text-xs"><option value="">Choose category</option>{catalogue.data?.categories.map(category => <option value={category.id} key={category.id}>{category.name}</option>)}</select><input aria-label="Field key" value={fieldDraft.fieldKey} onChange={event => setFieldDraft(current => ({ ...current, fieldKey: slugFor(event.target.value).replaceAll("-", "_") }))} placeholder="field_key" className="h-10 rounded-xl border border-slate-200 px-3 text-xs" /><input aria-label="Field label" value={fieldDraft.label} onChange={event => setFieldDraft(current => ({ ...current, label: event.target.value }))} placeholder="Field label" className="h-10 rounded-xl border border-slate-200 px-3 text-xs" /><select aria-label="Field type" value={fieldDraft.fieldType} onChange={event => setFieldDraft(current => ({ ...current, fieldType: event.target.value }))} className="h-10 rounded-xl border border-slate-200 bg-white px-3 text-xs">{["text", "textarea", "number", "currency", "boolean", "select", "multi_select", "date", "time", "image", "url", "phone", "email"].map(type => <option key={type} value={type}>{fieldLabel(type)}</option>)}</select><Button disabled={!fieldDraft.categoryId || !fieldDraft.fieldKey || !fieldDraft.label || createField.isPending} onClick={() => createField.mutate({ categoryId: Number(fieldDraft.categoryId), fieldKey: fieldDraft.fieldKey, label: fieldDraft.label, fieldType: fieldDraft.fieldType as "text" | "textarea" | "number" | "currency" | "boolean" | "select" | "multi_select" | "date" | "time" | "image" | "url" | "phone" | "email" })} className="h-10 rounded-xl bg-slate-950 text-xs hover:bg-slate-800">{createField.isPending ? "Adding…" : "Add field"}</Button></div> : <p className="mt-4 rounded-xl bg-slate-50 px-4 py-3 text-xs leading-5 text-slate-600">Field configuration remains visible to administrators but can only be changed by a super administrator.</p>}</section>}

    <section className="rounded-[20px] border border-indigo-100 bg-indigo-50/70 p-4"><div className="flex items-start gap-3"><Info className="mt-0.5 size-5 shrink-0 text-indigo-700" /><div><p className="text-sm font-bold text-indigo-950">Curated India coverage</p><p className="mt-1 text-xs leading-5 text-indigo-900">The public directory does not accept arbitrary city creation. Coverage is intentionally limited to the approved Just Finds India Tier-1 and Tier-2 catalogue. For an unsupported place, record a coverage request through the existing operational feedback process rather than creating a city record from this screen.</p></div></div></section>

    <Dialog open={newCategoryOpen} onOpenChange={setNewCategoryOpen}><DialogContent className="border-slate-200 bg-white text-slate-950"><DialogHeader><DialogTitle>Create a controlled category</DialogTitle><p className="text-sm leading-6 text-slate-500">New categories are created active. Review the name, icon metadata, and public availability before confirming.</p></DialogHeader><div className="grid gap-3"><label className="grid gap-1.5 text-xs font-semibold text-slate-700">Category name<input value={newCategory.name} onChange={event => setNewCategory(current => ({ ...current, name: event.target.value }))} placeholder="e.g. Dental clinics" className="h-10 rounded-xl border border-slate-200 px-3 text-sm" /></label><label className="grid gap-1.5 text-xs font-semibold text-slate-700">URL slug <input value={slugFor(newCategory.name)} readOnly className="h-10 rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm text-slate-500" /></label><label className="grid gap-1.5 text-xs font-semibold text-slate-700">Icon metadata<input value={newCategory.icon} onChange={event => setNewCategory(current => ({ ...current, icon: event.target.value }))} placeholder="Sparkles" className="h-10 rounded-xl border border-slate-200 px-3 text-sm" /></label><label className="grid gap-1.5 text-xs font-semibold text-slate-700">Description <textarea value={newCategory.description} onChange={event => setNewCategory(current => ({ ...current, description: event.target.value }))} placeholder="Optional internal description" className="min-h-24 rounded-xl border border-slate-200 p-3 text-sm" /></label>{createCategory.error && <p className="text-xs font-medium text-rose-700" role="alert">{createCategory.error.message}</p>}</div><DialogFooter><Button variant="outline" className="rounded-xl" onClick={() => setNewCategoryOpen(false)}>Cancel</Button><Button disabled={newCategory.name.trim().length < 2 || slugFor(newCategory.name).length < 2 || createCategory.isPending} onClick={() => createCategory.mutate({ name: newCategory.name.trim(), slug: slugFor(newCategory.name), description: newCategory.description.trim() || undefined, icon: newCategory.icon.trim() || "Sparkles" })} className="rounded-xl bg-indigo-700 hover:bg-indigo-800">{createCategory.isPending ? "Creating…" : "Create active category"}</Button></DialogFooter></DialogContent></Dialog>

    <Dialog open={Boolean(editingCategory)} onOpenChange={open => { if (!open) setEditingCategory(null); }}><DialogContent className="border-slate-200 bg-white text-slate-950"><DialogHeader><DialogTitle>Edit category governance</DialogTitle><p className="text-sm leading-6 text-slate-500">Core URL identity remains protected here. This control changes only displayed metadata and public availability.</p></DialogHeader>{editingCategory && <div className="grid gap-3"><div className="rounded-xl bg-slate-50 px-3 py-2"><p className="text-sm font-bold text-slate-900">{editingCategory.name}</p><p className="mt-0.5 text-xs text-slate-500">Category identity is immutable in this console.</p></div><label className="grid gap-1.5 text-xs font-semibold text-slate-700">Icon metadata<input value={editingCategory.icon} onChange={event => setEditingCategory(current => current ? { ...current, icon: event.target.value } : current)} className="h-10 rounded-xl border border-slate-200 px-3 text-sm" /></label><label className="grid gap-1.5 text-xs font-semibold text-slate-700">Description<textarea value={editingCategory.description} onChange={event => setEditingCategory(current => current ? { ...current, description: event.target.value } : current)} className="min-h-24 rounded-xl border border-slate-200 p-3 text-sm" /></label><label className="flex items-center justify-between rounded-xl border border-slate-200 px-3 py-3 text-sm font-semibold text-slate-800"><span>Active in listing workflows</span><input aria-label="Category active" type="checkbox" checked={editingCategory.isActive} onChange={event => setEditingCategory(current => current ? { ...current, isActive: event.target.checked } : current)} className="size-4 accent-indigo-700" /></label>{updateCategory.error && <p className="text-xs font-medium text-rose-700" role="alert">{updateCategory.error.message}</p>}</div>}<DialogFooter><Button variant="outline" className="rounded-xl" onClick={() => setEditingCategory(null)}>Cancel</Button><Button disabled={!editingCategory || updateCategory.isPending} onClick={() => editingCategory && updateCategory.mutate({ categoryId: editingCategory.id, description: editingCategory.description.trim() || null, icon: editingCategory.icon.trim() || "Sparkles", isActive: editingCategory.isActive })} className="rounded-xl bg-indigo-700 hover:bg-indigo-800">{updateCategory.isPending ? "Saving…" : "Save governance changes"}</Button></DialogFooter></DialogContent></Dialog>

    <AlertDialog open={Boolean(pendingCity)} onOpenChange={open => { if (!open) setPendingCity(null); }}><AlertDialogContent className="border-slate-200 bg-white text-slate-950"><AlertDialogHeader><AlertDialogTitle>{pendingCity?.cityId ? `${pendingCity.isActive ? "Pause" : "Activate"} ${pendingCity.name}?` : `Provision ${pendingCity?.name ?? "this city"}?`}</AlertDialogTitle><AlertDialogDescription>{pendingCity?.cityId ? "This changes whether the curated city can be selected in listings and imports. It does not create a new city or change its canonical state, tier, or coordinates." : "This provisions the canonical India Tier-1/Tier-2 catalogue record with its fixed state, tier, and coordinates. Arbitrary city details are not accepted."}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel className="rounded-xl">Cancel</AlertDialogCancel><AlertDialogAction disabled={createCity.isPending || setCityActive.isPending} onClick={() => { if (!pendingCity) return; if (pendingCity.cityId) setCityActive.mutate({ cityId: pendingCity.cityId, isActive: !pendingCity.isActive }); else createCity.mutate({ name: pendingCity.name }); }} className="rounded-xl bg-indigo-700 hover:bg-indigo-800">{createCity.isPending || setCityActive.isPending ? "Saving…" : pendingCity?.cityId ? "Confirm availability change" : "Provision canonical city"}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </section>;
}

function CategoryTable({ categories, isSuperAdmin, onEdit }: { categories: Array<{ id: number; name: string; slug: string; description: string | null; icon: string; isActive: boolean; status: "active" | "inactive"; subcategoryCount: number; fieldCount: number }>; isSuperAdmin: boolean; onEdit: (category: { id: number; name: string; description: string | null; icon: string; isActive: boolean }) => void }) {
  return <div className="overflow-x-auto"><table className="min-w-[780px] w-full text-left"><thead className="border-y border-slate-100 bg-slate-50 text-[10px] font-extrabold uppercase tracking-[.1em] text-slate-500"><tr><th className="px-5 py-3">Category</th><th className="px-4 py-3">Structure</th><th className="px-4 py-3">Icon metadata</th><th className="px-4 py-3">Activation</th><th className="px-5 py-3 text-right">Control</th></tr></thead><tbody className="divide-y divide-slate-100">{categories.length ? categories.map(category => <tr key={category.id} className="hover:bg-slate-50/70"><td className="px-5 py-4"><p className="text-sm font-bold text-slate-900">{category.name}</p><p className="mt-1 font-mono text-[11px] text-slate-500">/{category.slug}</p></td><td className="px-4 py-4 text-xs text-slate-600"><span className="font-semibold text-slate-800">{category.subcategoryCount}</span> subcategories · <span className="font-semibold text-slate-800">{category.fieldCount}</span> fields</td><td className="px-4 py-4"><code className="rounded-md bg-slate-100 px-2 py-1 text-[11px] font-semibold text-slate-700">{category.icon}</code></td><td className="px-4 py-4"><Status active={category.isActive && category.status === "active"} activeLabel="Active" inactiveLabel="Inactive" /></td><td className="px-5 py-4 text-right">{isSuperAdmin ? <Button variant="outline" className="h-8 rounded-lg border-slate-200 bg-white text-xs" onClick={() => onEdit(category)}><Edit3 className="mr-1.5 size-3.5" />Edit governance</Button> : <span className="text-xs font-medium text-slate-400">Restricted</span>}</td></tr>) : <tr><td colSpan={5} className="px-5 py-12 text-center text-sm text-slate-500">No category record matches this search.</td></tr>}</tbody></table></div>;
}

function CityTable({ cities, isSuperAdmin, onAction }: { cities: Array<{ cityId: number | null; name: string; slug: string; state: string; country: "IN"; tier: "tier1" | "tier2"; latitude: string; longitude: string; isProvisioned: boolean; isActive: boolean }>; isSuperAdmin: boolean; onAction: (action: CityAction) => void }) {
  return <div className="overflow-x-auto"><table className="min-w-[920px] w-full text-left"><thead className="border-y border-slate-100 bg-slate-50 text-[10px] font-extrabold uppercase tracking-[.1em] text-slate-500"><tr><th className="px-5 py-3">City</th><th className="px-4 py-3">Tier</th><th className="px-4 py-3">State</th><th className="px-4 py-3">Coordinates</th><th className="px-4 py-3">Catalogue state</th><th className="px-5 py-3 text-right">Control</th></tr></thead><tbody className="divide-y divide-slate-100">{cities.length ? cities.map(city => <tr key={city.slug} className="hover:bg-slate-50/70"><td className="px-5 py-4"><div className="flex items-center gap-2"><MapPin className="size-4 text-slate-400" /><div><p className="text-sm font-bold text-slate-900">{city.name}</p><p className="mt-1 font-mono text-[11px] text-slate-500">/{city.slug}</p></div></div></td><td className="px-4 py-4"><span className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${city.tier === "tier1" ? "bg-indigo-50 text-indigo-800" : "bg-slate-100 text-slate-700"}`}>{city.tier === "tier1" ? "Tier 1" : "Tier 2"}</span></td><td className="px-4 py-4 text-xs font-medium text-slate-700">{city.state}</td><td className="px-4 py-4 font-mono text-[11px] text-slate-600">{city.latitude}, {city.longitude}</td><td className="px-4 py-4">{city.isProvisioned ? <Status active={city.isActive} activeLabel="Active" inactiveLabel="Paused" /> : <span className="inline-flex items-center gap-1.5 rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-bold text-slate-600"><CircleOff className="size-3.5" />Not provisioned</span>}</td><td className="px-5 py-4 text-right">{isSuperAdmin ? <Button variant="outline" className="h-8 rounded-lg border-slate-200 bg-white text-xs" onClick={() => onAction({ cityId: city.cityId ?? 0, name: city.name, isActive: city.isActive })}>{city.isProvisioned ? city.isActive ? "Pause availability" : "Activate city" : <><MapPinned className="mr-1.5 size-3.5" />Provision</>}</Button> : <span className="text-xs font-medium text-slate-400">Curated record</span>}</td></tr>) : <tr><td colSpan={6} className="px-5 py-12 text-center text-sm text-slate-500">No approved India city matches this search.</td></tr>}</tbody></table></div>;
}

function Status({ active, activeLabel, inactiveLabel }: { active: boolean; activeLabel: string; inactiveLabel: string }) { return <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[11px] font-bold ${active ? "bg-emerald-50 text-emerald-800" : "bg-amber-50 text-amber-900"}`}>{active ? <CheckCircle2 className="size-3.5" /> : <CircleOff className="size-3.5" />}{active ? activeLabel : inactiveLabel}</span>; }
