import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ExternalLink, FileText, Loader2, ShieldCheck } from "lucide-react";
import { useState } from "react";

function EvidenceLink({ businessId, documentId, filename }: { businessId: number; documentId: number; filename: string }) {
  const document = trpc.business.verificationDocumentUrl.useQuery({ businessId, documentId });
  if (document.isLoading) return <span className="inline-flex items-center gap-1 text-xs text-slate-500"><Loader2 className="size-3 animate-spin" />Preparing secure file</span>;
  if (!document.data?.url) return <span className="text-xs text-rose-700">Evidence unavailable</span>;
  return <a href={document.data.url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-xs font-semibold text-[#173d9c] hover:underline"><FileText className="size-3.5" />{filename}<ExternalLink className="size-3" /></a>;
}

export function VerificationReviewQueue() {
  const utils = trpc.useUtils();
  const queue = trpc.business.verificationQueue.useQuery();
  const [notes, setNotes] = useState<Record<number, string>>({});
  const review = trpc.business.reviewVerification.useMutation({ onSuccess: () => void utils.business.verificationQueue.invalidate() });
  if (queue.isLoading) return <div className="mt-8 grid min-h-40 place-items-center text-sm text-slate-500"><Loader2 className="size-5 animate-spin" /></div>;
  if (queue.error) return <div className="mt-8 rounded-2xl border border-rose-200 bg-rose-50 p-5 text-sm text-rose-800">{queue.error.message}</div>;
  return <section className="mt-8 space-y-4"><div className="rounded-2xl border border-blue-100 bg-blue-50 p-5"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 size-5 text-[#173d9c]" /><div><h2 className="font-semibold text-slate-900">Private evidence review</h2><p className="mt-1 text-sm leading-6 text-slate-600">Review the submitted business evidence and record a specific decision. A verification decision only controls the verified badge; it does not change listing facts or publication state.</p></div></div></div>{queue.data?.length ? queue.data.map(({ verification, business, ownerName, documents }) => { const note = notes[business.id] ?? ""; return <article className="rounded-2xl border border-slate-200 bg-white p-5" key={verification.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold text-slate-900">{business.name}</p><p className="mt-1 text-sm text-slate-500">Owner: {ownerName || "Unknown"} · Submitted {verification.submittedAt ? new Date(verification.submittedAt).toLocaleString() : "recently"}</p>{verification.submissionNote && <p className="mt-3 max-w-3xl rounded-xl bg-slate-50 p-3 text-sm leading-6 text-slate-700">Owner note: {verification.submissionNote}</p>}</div><span className="rounded-full bg-amber-100 px-2.5 py-1 text-xs font-semibold text-amber-900">Pending review</span></div><div className="mt-4 grid gap-2">{documents.map(document => <div className="flex flex-wrap items-center justify-between gap-2 rounded-xl bg-slate-50 px-3 py-2.5" key={document.id}><EvidenceLink businessId={business.id} documentId={document.id} filename={document.fileName} /><span className="text-xs capitalize text-slate-500">{document.documentType.replaceAll("_", " ")} · {Math.ceil(document.fileSize / 1024)} KB</span></div>)}</div><label className="mt-4 block text-sm font-medium text-slate-700">Decision note<textarea className="field mt-1 min-h-20" value={note} onChange={event => setNotes(current => ({ ...current, [business.id]: event.target.value }))} placeholder="State the evidence basis or the changes the owner must make." /></label><div className="mt-3 flex flex-wrap gap-2"><Button disabled={review.isPending || note.trim().length < 5} className="rounded-xl bg-emerald-700 hover:bg-emerald-800" onClick={() => review.mutate({ businessId: business.id, decision: "verified", note })}>Verify business</Button><Button disabled={review.isPending || note.trim().length < 5} variant="outline" className="rounded-xl bg-white text-amber-800" onClick={() => review.mutate({ businessId: business.id, decision: "changes_requested", note })}>Request changes</Button></div></article>; }) : <div className="rounded-2xl border border-emerald-100 bg-emerald-50 p-6 text-sm text-emerald-900">No verification evidence is awaiting review.</div>}{review.error && <p className="text-sm text-rose-700">{review.error.message}</p>}</section>;
}
