import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { canRecordVerificationDecision, filterVerificationCases, type VerificationQueueFilter, verificationQueueFilters, verificationReviewGuidance } from "@/lib/verificationReviewPresentation";
import { CheckCircle2, ChevronRight, CircleAlert, FileText, Loader2, Search, ShieldCheck } from "lucide-react";
import { useMemo, useState } from "react";

function EvidenceOpenButton({ businessId, documentId, filename }: { businessId: number; documentId: number; filename: string }) {
  const document = trpc.business.verificationDocumentUrl.useQuery({ businessId, documentId }, { enabled: false });
  const openEvidence = async () => {
    const result = await document.refetch();
    if (result.data?.url) window.open(result.data.url, "_blank", "noopener,noreferrer");
  };
  return <Button type="button" variant="outline" size="sm" disabled={document.isFetching} onClick={() => void openEvidence()} className="h-9 rounded-lg bg-white text-xs text-[var(--jf-primary)]">{document.isFetching ? <Loader2 className="mr-1.5 size-3.5 animate-spin" /> : <FileText className="mr-1.5 size-3.5" />}Open evidence<span className="sr-only">: {filename}</span></Button>;
}

export function VerificationReviewQueue() {
  const utils = trpc.useUtils();
  const queue = trpc.business.verificationQueue.useQuery();
  const [filter, setFilter] = useState<VerificationQueueFilter>("all");
  const [query, setQuery] = useState("");
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const [notes, setNotes] = useState<Record<number, string>>({});
  const [confirming, setConfirming] = useState<"verified" | "changes_requested" | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  const review = trpc.business.reviewVerification.useMutation({
    onSuccess: result => {
      setNotice(result.status === "verified" ? "Verification decision recorded." : "Change request recorded.");
      setSelectedId(null);
      setConfirming(null);
      void utils.business.verificationQueue.invalidate();
    },
  });
  const visibleCases = useMemo(() => filterVerificationCases(queue.data ?? [], filter, query), [filter, query, queue.data]);
  const selectedCase = visibleCases.find(item => item.business.id === selectedId) ?? visibleCases[0];
  const selectedNote = selectedCase ? notes[selectedCase.business.id] ?? "" : "";
  const canDecide = canRecordVerificationDecision(selectedNote);

  if (queue.isLoading) return <section className="mt-8 grid min-h-56 place-items-center rounded-[24px] border border-[var(--jf-border)] bg-white text-sm text-[var(--jf-muted)]"><Loader2 className="size-5 animate-spin" /></section>;
  if (queue.error) return <section className="mt-8 rounded-[24px] border border-rose-200 bg-rose-50 p-6 text-sm text-rose-800"><CircleAlert className="mb-2 size-5" />{queue.error.message}</section>;

  return <section className="mt-8 space-y-5">
    <header className="rounded-[24px] border border-blue-100 bg-blue-50/70 p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div className="max-w-2xl"><div className="flex items-center gap-2 text-[11px] font-bold uppercase tracking-[.14em] text-[var(--jf-primary)]"><ShieldCheck className="size-4" />Verification review</div><h2 className="mt-2 text-xl font-semibold tracking-[-.03em] text-[var(--jf-text)]">Review evidence carefully before deciding</h2><p className="mt-2 text-sm leading-6 text-[var(--jf-muted)]">A decision controls only the verified state. It does not publish the listing or alter its facts. Evidence remains private and opens only when an administrator explicitly requests it.</p></div><span className="rounded-xl border border-blue-200 bg-white px-3 py-2 text-xs font-bold text-[var(--jf-primary)]">{queue.data?.length ?? 0} pending</span></div></header>
    {notice && <div role="status" className="flex items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-900"><CheckCircle2 className="size-4" />{notice}</div>}
    <div className="flex flex-col gap-3 rounded-[20px] border border-[var(--jf-border)] bg-white p-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex flex-wrap gap-2" aria-label="Verification queue filters">{verificationQueueFilters.map(item => <button key={item.value} onClick={() => setFilter(item.value)} className={`min-h-10 rounded-xl px-3 text-xs font-bold transition-colors ${filter === item.value ? "bg-[var(--jf-primary)] text-white" : "bg-slate-50 text-slate-600 hover:bg-slate-100"}`}>{item.label}</button>)}</div><label className="relative block sm:w-64"><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400" /><input value={query} onChange={event => setQuery(event.target.value)} className="field h-10 w-full pl-9" placeholder="Find a business" aria-label="Find a business in the verification queue" /></label></div>
    {!visibleCases.length ? <div className="rounded-[24px] border border-dashed border-slate-300 bg-slate-50 p-8 text-center text-sm leading-6 text-[var(--jf-muted)]">No pending cases match these filters. Change the queue filter or clear the business search.</div> : <div className="grid gap-5 xl:grid-cols-[minmax(280px,.75fr)_minmax(0,1.25fr)]"><aside className="overflow-hidden rounded-[24px] border border-[var(--jf-border)] bg-white"><div className="border-b border-[var(--jf-border)] px-4 py-3"><p className="text-xs font-bold uppercase tracking-[.13em] text-[var(--jf-muted)]">Pending cases</p></div><div className="max-h-[640px] overflow-y-auto p-2">{visibleCases.map(item => { const active = selectedCase?.business.id === item.business.id; return <button key={item.verification.id} onClick={() => { setSelectedId(item.business.id); setConfirming(null); }} className={`flex w-full items-start gap-3 rounded-2xl p-3 text-left transition-colors ${active ? "bg-blue-50 ring-1 ring-blue-200" : "hover:bg-slate-50"}`}><span className={`mt-1.5 size-2 shrink-0 rounded-full ${item.documents.length ? "bg-emerald-500" : "bg-amber-500"}`} aria-hidden="true" /><span className="min-w-0 flex-1"><span className="block truncate text-sm font-bold text-[var(--jf-text)]">{item.business.name}</span><span className="mt-1 block truncate text-xs text-[var(--jf-muted)]">{item.categoryName ?? "Category unavailable"} · {item.cityName ?? "City unavailable"}</span><span className="mt-2 block text-[11px] font-semibold text-slate-500">{item.documents.length} evidence {item.documents.length === 1 ? "file" : "files"}</span></span><ChevronRight className="mt-2 size-4 shrink-0 text-slate-400" /></button>; })}</div></aside>
      {selectedCase && <article className="rounded-[24px] border border-[var(--jf-border)] bg-white"><div className="border-b border-[var(--jf-border)] p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[11px] font-bold uppercase tracking-[.14em] text-[var(--jf-primary)]">Selected verification case</p><h3 className="mt-1 text-xl font-semibold tracking-[-.03em] text-[var(--jf-text)]">{selectedCase.business.name}</h3><p className="mt-1 text-sm text-[var(--jf-muted)]">Submitted {selectedCase.verification.submittedAt ? new Date(selectedCase.verification.submittedAt).toLocaleString() : "without a recorded submission time"}</p></div><span className="rounded-xl bg-amber-100 px-3 py-2 text-xs font-bold text-amber-900">Pending review</span></div></div>
        <div className="grid gap-5 p-5 sm:p-6 lg:grid-cols-2"><section><h4 className="text-sm font-bold text-[var(--jf-text)]">Business facts</h4><dl className="mt-3 grid gap-3 rounded-2xl bg-slate-50 p-4 text-sm"><div><dt className="text-xs font-semibold text-[var(--jf-muted)]">Category and city</dt><dd className="mt-1 font-medium text-slate-800">{selectedCase.categoryName ?? "Not recorded"} · {selectedCase.cityName ?? "Not recorded"}</dd></div><div><dt className="text-xs font-semibold text-[var(--jf-muted)]">Listing state</dt><dd className="mt-1 font-medium capitalize text-slate-800">{selectedCase.business.status.replaceAll("_", " ")}</dd></div><div><dt className="text-xs font-semibold text-[var(--jf-muted)]">Business address</dt><dd className="mt-1 whitespace-pre-wrap font-medium text-slate-800">{selectedCase.business.address}</dd></div></dl>{selectedCase.verification.submissionNote && <div className="mt-4 rounded-2xl border border-slate-200 p-4"><p className="text-xs font-bold uppercase tracking-[.12em] text-[var(--jf-muted)]">Owner submission note</p><p className="mt-2 text-sm leading-6 text-slate-700">{selectedCase.verification.submissionNote}</p></div>}</section>
          <section><div className="flex items-center justify-between gap-3"><h4 className="text-sm font-bold text-[var(--jf-text)]">Private evidence</h4><span className="text-xs font-semibold text-[var(--jf-muted)]">{selectedCase.documents.length} attached</span></div><p className="mt-2 text-sm leading-6 text-[var(--jf-muted)]">{verificationReviewGuidance(selectedCase.documents.length)}</p><div className="mt-3 grid gap-2">{selectedCase.documents.length ? selectedCase.documents.map(document => <div className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-slate-200 p-3" key={document.id}><div className="min-w-0"><p className="truncate text-sm font-semibold text-slate-800">{document.fileName}</p><p className="mt-1 text-xs capitalize text-[var(--jf-muted)]">{document.documentType.replaceAll("_", " ")} · {Math.ceil(document.fileSize / 1024)} KB</p></div><EvidenceOpenButton businessId={selectedCase.business.id} documentId={document.id} filename={document.fileName} /></div>) : <div className="rounded-2xl border border-dashed border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">No evidence is attached to this pending case.</div>}</div></section></div>
        <div className="border-t border-[var(--jf-border)] p-5 sm:p-6"><div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_minmax(230px,.7fr)]"><section><label className="block text-sm font-bold text-[var(--jf-text)]">Required decision explanation<span className="text-rose-700"> *</span><textarea className="field mt-2 min-h-28" value={selectedNote} onChange={event => setNotes(current => ({ ...current, [selectedCase.business.id]: event.target.value }))} placeholder="State what you reviewed and the basis for your verification or change request." /></label><p className="mt-2 text-xs leading-5 text-[var(--jf-muted)]">This explanation is recorded with the decision and becomes visible in the business verification history.</p>{review.error && <p className="mt-3 text-sm text-rose-700">{review.error.message}</p>}<div className="mt-4 flex flex-wrap gap-2"><Button disabled={!canDecide || review.isPending} onClick={() => setConfirming("verified")} className="min-h-11 rounded-xl bg-emerald-700 hover:bg-emerald-800">Verify business</Button><Button disabled={!canDecide || review.isPending} variant="outline" onClick={() => setConfirming("changes_requested")} className="min-h-11 rounded-xl border-amber-300 bg-white text-amber-900 hover:bg-amber-50">Request changes</Button></div>{confirming && <div className="mt-4 rounded-2xl border border-slate-200 bg-slate-50 p-4"><p className="text-sm font-bold text-slate-900">Confirm: {confirming === "verified" ? "verify this business" : "request changes"}</p><p className="mt-1 text-xs leading-5 text-slate-600">This records the required explanation in the immutable verification history. It does not publish or edit the listing.</p><div className="mt-3 flex flex-wrap gap-2"><Button disabled={review.isPending} onClick={() => review.mutate({ businessId: selectedCase.business.id, decision: confirming, note: selectedNote.trim() })} className={`min-h-10 rounded-xl ${confirming === "verified" ? "bg-emerald-700 hover:bg-emerald-800" : "bg-amber-700 hover:bg-amber-800"}`}>{review.isPending && <Loader2 className="mr-2 size-4 animate-spin" />}Confirm decision</Button><Button disabled={review.isPending} variant="outline" onClick={() => setConfirming(null)} className="min-h-10 rounded-xl bg-white">Cancel</Button></div></div>}</section>
            <aside className="rounded-2xl bg-slate-50 p-4"><h4 className="text-sm font-bold text-[var(--jf-text)]">Immutable case history</h4><p className="mt-1 text-xs leading-5 text-[var(--jf-muted)]">Recorded case events cannot be edited from this review screen.</p><div className="mt-4 space-y-3">{selectedCase.events.length ? selectedCase.events.map(event => <div className="rounded-xl border border-white bg-white p-3" key={event.id}><p className="text-sm font-semibold capitalize text-slate-800">{event.action.replaceAll("_", " ")}</p>{event.note && <p className="mt-1 text-xs leading-5 text-slate-600">{event.note}</p>}<p className="mt-2 text-[11px] text-slate-500">{new Date(event.createdAt).toLocaleString()}</p></div>) : <p className="rounded-xl bg-white p-3 text-sm leading-6 text-[var(--jf-muted)]">No recorded case events are available.</p>}</div></aside></div></div>
      </article>}</div>}
  </section>;
}
