import { startLogin } from "@/const";
import { JustFindsLogo } from "@/components/JustFindsLogo";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/_core/hooks/useAuth";
import { cn } from "@/lib/utils";
import { ArrowLeft, ChevronRight, LogOut, Menu, X } from "lucide-react";
import { useState } from "react";
import { Link, useLocation } from "wouter";

export type WorkspaceNavItem = { href: string; label: string; icon: React.ElementType };

export function WorkspaceShell({ title, subtitle, items, children, requireAdmin = false }: { title: string; subtitle: string; items: WorkspaceNavItem[]; children: React.ReactNode; requireAdmin?: boolean }) {
  const { user, loading, logout } = useAuth();
  const [location] = useLocation();
  const [open, setOpen] = useState(false);
  const adminAllowed = user?.role === "admin" || user?.role === "super_admin";
  if (loading) return <div className="min-h-screen bg-[#f7f8fa] p-6"><div className="h-10 w-32 animate-pulse rounded-xl bg-slate-200" /><div className="mt-10 h-80 animate-pulse rounded-3xl bg-slate-100" /></div>;
  if (!user || (requireAdmin && !adminAllowed)) return <div className="grid min-h-screen place-items-center bg-[#f7f8fa] p-5"><div className="max-w-md rounded-[28px] border border-slate-200 bg-white p-8 text-center shadow-[0_18px_55px_rgba(15,23,42,.10)]"><JustFindsLogo /><h1 className="mt-8 text-2xl font-semibold tracking-[-.045em] text-slate-950">{requireAdmin && user ? "Administrator access required" : "Sign in to continue"}</h1><p className="mt-3 text-sm leading-6 text-slate-500">{requireAdmin && user ? "This workspace is protected for Just Finds administrators." : "Business and administration workspaces use your Just Finds account to keep data isolated."}</p><div className="mt-7 flex justify-center gap-3"><Link href="/"><Button variant="outline" className="rounded-xl bg-white"><ArrowLeft className="mr-2 size-4" />Home</Button></Link>{!user && <Button onClick={() => startLogin()} className="rounded-xl bg-[#173d9c]">Sign in</Button>}</div></div></div>;
  return <div className="min-h-screen bg-[#f7f8fa] text-slate-950"><a href="#workspace-main" className="skip-link">Skip to workspace content</a><div className="flex min-h-screen"><aside className={cn("fixed inset-y-0 left-0 z-50 flex w-[278px] flex-col border-r border-slate-200 bg-white p-4 transition-transform duration-200 md:sticky md:translate-x-0", open ? "translate-x-0" : "-translate-x-full")}><div className="flex items-center justify-between px-2 py-2"><JustFindsLogo /><button onClick={() => setOpen(false)} className="grid size-9 place-items-center rounded-xl hover:bg-slate-100 md:hidden"><X className="size-4" /></button></div><div className="mt-7 px-2"><p className="text-[11px] font-semibold uppercase tracking-[.14em] text-slate-400">{title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{subtitle}</p></div><nav className="mt-6 grid gap-1" aria-label={`${title} navigation`}>{items.map(item => { const active = location === item.href; return <Link href={item.href} key={item.href} onClick={() => setOpen(false)} className={cn("flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition-colors", active ? "bg-[#eaf0ff] text-[#173d9c]" : "text-slate-600 hover:bg-slate-100 hover:text-slate-900")}><item.icon className="size-[18px]" />{item.label}{active && <ChevronRight className="ml-auto size-4" />}</Link>; })}</nav><div className="mt-auto rounded-2xl bg-[#f7f8fa] p-3"><div className="flex items-center gap-2.5"><span className="grid size-9 place-items-center rounded-xl bg-[#173d9c] text-sm font-semibold text-white">{user.name?.slice(0, 1).toUpperCase() ?? "J"}</span><div className="min-w-0"><p className="truncate text-xs font-semibold text-slate-800">{user.name ?? "Just Finds user"}</p><p className="truncate text-[11px] text-slate-500">{user.role.replace(/_/g, " ")}</p></div></div><button onClick={logout} className="mt-3 flex w-full items-center gap-2 rounded-xl px-2 py-2 text-xs font-semibold text-slate-500 hover:bg-white hover:text-slate-800"><LogOut className="size-3.5" />Sign out</button></div></aside>{open && <button onClick={() => setOpen(false)} className="fixed inset-0 z-40 bg-slate-950/25 md:hidden" aria-label="Close menu" />}<div className="min-w-0 flex-1"><header className="sticky top-0 z-30 flex h-[70px] items-center border-b border-slate-200 bg-[#f7f8fa]/90 px-4 backdrop-blur md:px-8"><button onClick={() => setOpen(true)} className="mr-3 grid size-9 place-items-center rounded-xl hover:bg-white md:hidden"><Menu className="size-4" /></button><div><p className="text-sm font-semibold text-slate-900">{title}</p><p className="text-xs text-slate-500">{subtitle}</p></div><Link href="/" className="ml-auto text-xs font-semibold text-[#1f51c8]">View public site</Link></header><main id="workspace-main" tabIndex={-1} className="p-4 pb-24 md:p-8 md:pb-10">{children}</main></div></div></div>;
}
